### ISSUE TITLE
Evolution does not decrease as expected

### ISSUE THREAD

**Issue by totobest** [veden/rampantEvolution#4]
Factorio 1.1.50
RampantEvolution_1.3.0

With these settings:
![2022-01-06 20_52_58-Factorio 1 1 50](https://user-images.githubusercontent.com/11507846/148443865-592e9d81-ce67-4030-a512-62500fb1733c.png)
The result of the command /rampantEvolution gives:
![2022-01-06 21_11_50-Factorio 1 1 50](https://user-images.githubusercontent.com/11507846/148445373-f6881919-0105-4d15-ae61-41a2e6e64fdc.png)

I would like that the evolution decreases more by the time so I changed the setting "Evolution per second elapsed" to -10:
![2022-01-06 20_52_32-Factorio 1 1 50](https://user-images.githubusercontent.com/11507846/148445456-6cc62b49-e363-41c4-bdb5-40daebe1b4bb.png)
and it gives (I waited for the recalculation to be finished):
![2022-01-06 21_09_33-Factorio 1 1 50](https://user-images.githubusercontent.com/11507846/148446183-ae64c598-d362-42cc-a757-96f5e84835cf.png)

I'm surprised that it did not affect that much the global evolution the others factors increased like the **Absorbed pollution by spawner**. Is it normal?

**Comment by totobest** [comment]
I tried with changing the same setting to -100 and used gvv to watch the global values. Here the result:
![image](https://user-images.githubusercontent.com/11507846/148449274-3099c7d8-660d-4f9b-b9a7-5807b0fe7539.png)

Evolution is still above 0.9. I would expect evolution to decrease drastically.

**Comment by veden** [comment]
Without a save, this is much harder to answer.
Something to keep in mind is that the contributions are absolute contributions to the evolution and that the affects are not linear they are (1 - evo)^2. 
Also all numbers are scaled by 1e-7 but it is easier to talk in whole units.
Each mod setting corresponds to either 1 kill, 1 pollution, or 1 second and is applied to the current evolution using (1-evo)^2.

So a killed spawner is worth 1000 in the mod settings. At 0% evolution, the killed spawner contributes the full 1000. At 50% evolution that contribution is 250. At 94.84% your 1000 per spawner kill is now only worth 2.66256

When you have negative numbers, they make the positive contributions larger because (1-evo)^2 is getting bigger as you reduce the evolution. 

Some quick math. If you have -100 per time which is -100 per second. A boiler creates pollution at 30/min, so to talk about equal units we multiple -100 by 60 to get evolution reduction per minute with respect to the time. So at -6000 minute that is roughly equivalent to 200 boilers and the reduction is completely counter.
Or if you want to talk about spawners, that same -6000 reduction is completely countered by 380 pollution absorbed by spawners in a minute at 15.75.
This calculation isn't perfect, but should give some idea of the numbers involved.

If none of this answered your question or you still think something is wrong, please ask additional questions and/or post your save.

**Comment by totobest** [comment]
Thank you for the detailed explaination. It makes sense in general though I think the behavior in game could be more predictable : If I decrease the evolution per second ellapsed; the evolution should decrease right?

Here the (big) save : https://www.dropbox.com/s/wzyk1wxrasktxn7/ks2sett.zip?dl=0


I'll play more with the config in the meantime.

**Comment by veden** [comment]
yes to evolution should decrease.
Do you have any suggestions on how to make the behavior more predictable?
